name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.npm_token }}
      - name: Install Deps
        run: npm install
      - name: Publish
        run: npm publish
